### ISSUE TITLE
Socket error when sending iOS notifications

### ISSUE THREAD

**Issue by mario** [parse-server-modules/parse-server-push-adapter#42]
Using NodeJS 7.0, PM2 and latest Parse server & parse-server-push-adapter on DigitalOcean I get socket error. Firewall is not a problem as outgoing connections are not blocked. (That's using verbose logging). Any idea what's happening? I've tested the certificate differently and it works, but doesn't work using parse. PUSH configuration sample I'm using:

      "PARSE_SERVER_PUSH": {
        android: {
          senderId: '',
          apiKey: ''
        },
        ios: [
        {
          pfx: '',
          bundleId: '',
          production: false
          },
        {
          pfx: '', 
          bundleId: '',  
          production: true
        }
        ]
      }

Any help is appreciated!

**Comment by mario** [comment]
More stuff :)

0|parse-wr | Sat, 05 Nov 2016 15:48:12 GMT apn Error: multiple keys found in PFX/P12 file
0|parse-wr |     at /usr/lib/node_modules/parse-server/node_modules/apn/lib/credentials/parsePkcs12.js:46:12
0|parse-wr |     at Array.forEach (native)
0|parse-wr |     at /usr/lib/node_modules/parse-server/node_modules/apn/lib/credentials/parsePkcs12.js:43:25
0|parse-wr |     at Array.forEach (native)
0|parse-wr |     at apnCredentialsFromPkcs12 (/usr/lib/node_modules/parse-server/node_modules/apn/lib/credentials/parsePkcs12.js:42:22)
0|parse-wr |     at parse (/usr/lib/node_modules/parse-server/node_modules/apn/lib/credentials/parse.js:11:21)
0|parse-wr |     at /usr/lib/node_modules/parse-server/node_modules/apn/lib/connection.js:156:15
0|parse-wr |     at _fulfilled (/usr/lib/node_modules/parse-server/node_modules/q/q.js:834:54)
0|parse-wr |     at self.promiseDispatch.done (/usr/lib/node_modules/parse-server/node_modules/q/q.js:863:30)
0|parse-wr |     at Promise.promise.promiseDispatch (/usr/lib/node_modules/parse-server/node_modules/q/q.js:796:13)
0|parse-wr | Sat, 05 Nov 2016 15:48:12 GMT apn Socket error occurred undefined { Error: socket hang up
0|parse-wr |     at TLSSocket.onHangUp (_tls_wrap.js:1094:19)
0|parse-wr |     at TLSSocket.g (events.js:291:16)
0|parse-wr |     at emitNone (events.js:91:20)
0|parse-wr |     at TLSSocket.emit (events.js:185:7)
0|parse-wr |     at endReadableNT (_stream_readable.js:974:12)
0|parse-wr |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
0|parse-wr |     at process._tickDomainCallback (internal/process/next_tick.js:122:9) code: 'ECONNRESET' }
0|parse-wr | Sat, 05 Nov 2016 15:48:12 GMT apn Destroying connection undefined
0|parse-wr | Sat, 05 Nov 2016 15:48:12 GMT apn Removing socket from pool undefined
0|parse-wr | Sat, 05 Nov 2016 15:48:12 GMT apn Raising error: { Error: socket hang up
0|parse-wr |     at TLSSocket.onHangUp (_tls_wrap.js:1094:19)
0|parse-wr |     at TLSSocket.g (events.js:291:16)
0|parse-wr |     at emitNone (events.js:91:20)
0|parse-wr |     at TLSSocket.emit (events.js:185:7)
0|parse-wr |     at endReadableNT (_stream_readable.js:974:12)
0|parse-wr |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
0|parse-wr |     at process._tickDomainCallback (internal/process/next_tick.js:122:9) code: 'ECONNRESET' } undefined undefined
0|parse-wr | Sat, 05 Nov 2016 15:48:12 GMT apn Error occurred with trace: Error: socket hang up
0|parse-wr |     at TLSSocket.onHangUp (_tls_wrap.js:1094:19)
0|parse-wr |     at TLSSocket.g (events.js:291:16)
0|parse-wr |     at emitNone (events.js:91:20)
0|parse-wr |     at TLSSocket.emit (events.js:185:7)
0|parse-wr |     at endReadableNT (_stream_readable.js:974:12)
0|parse-wr |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
0|parse-wr |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
0|parse-wr | verb
0|parse-wr |  
0|parse-wr | parse-server-push-adapter APNS
0|parse-wr |  APNS Connection 0 Socket Error
0|parse-wr | Sat, 05 Nov 2016 15:48:12 GMT apn Socket closed undefined
0|parse-wr | Sat, 05 Nov 2016 15:48:12 GMT apn Removing socket from pool undefined
0|parse-wr | verb
0|parse-wr |

**Comment by mario** [comment]
Nevermind, had the wrong certs :-/
